### ISSUE TITLE
Criteria for registration need to be decided

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/toplevel#1]
In -00, there is a list of potential criteria, but not yet a proposed list of criteria that the IETF should adopt.

From HTA's review:

When we go to pick arguments to make into criteria, I think we should pick:

* Must be a Standards Track RFC (don’t see a reason to skip that one)
* Must be well defined - it’s clear what goes in and what doesn’t go in. (Application/ was the original grab bag. We only need one.)
* Must have a community of interest that says “we’ll use it” with some credibility
* Should not generate aliases for existing widely used MIME types

**Comment by duerst** [comment]
The criteria are now in Section 2, which has various subsections. There was also a comment on the mailing list that "Should not generate aliases for existing widely used MIME types" may be too strong.

**Comment by alvestrand** [comment]
I'm closing this as "done in -01", we should open new issues for iterating on specific criteria (like the "not generate aliases" one).
