### ISSUE TITLE
IANA: Reference IANA registry policy

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/toplevel#13]
IANA has a page at https://www.iana.org/help/protocol-registration about how to write IANA considerations section.

The current guidelines RFC is https://www.rfc-editor.org/rfc/rfc8126.html - the policy we want to reference is https://www.rfc-editor.org/rfc/rfc8126.html#section-4.9 Standards Action.

**Comment by duerst** [comment]
Addressed (hopefully) with
https://github.com/ietf-wg-mediaman/toplevel/commit/75ec105acf1c and
https://github.com/ietf-wg-mediaman/toplevel/commit/c3268e9fb28b.

**Comment by alvestrand** [comment]
Addressed in -04
