### ISSUE TITLE
Give precise IANA instructions in IANA considerations section

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/toplevel#14]
The things that IANA are supposed to check for should be listed in section 4.1.

This includes (and, I think, is limited to):

- Policy is "standards action" ("RFC required" is wrong, you want section 4.9 not 4.7 of 8126)
- IANA considerations MUST request addition to the registry
- At least one actual subtype SHOULD exist - only allowed exception is if registering something for demonstration purposes only.
- Security considerations MUST be documented

**Comment by duerst** [comment]
- Changed policy to "standards action" (commit 41b1d2501dd7)
- Mentioned the other things listed by @alvestrand (commits 64ce44b74748, e6bad09b47f0)
