### ISSUE TITLE
Effects of registering a top level type need to be described

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/toplevel#2]
From HTA's review:

The technical benefit of new top-level types is low. There can be some benefits for human consumption of information on non-recognized types (such as icons), but most technical objectives are no more or less easy to achieve than with subtypes of application/

We should probably get consensus language in the draft for such a description, to set expectations right.

**Comment by duerst** [comment]
There is some information on this now in "1.1.  Background", mainly in the first two paragraphs. Any proposals for improvement appreciated.

**Comment by alvestrand** [comment]
I think the "dispatching code" in section 2.2 adequately describes the technical benefit.
Happy to close this issue with "no further changes needed over -01".

**Comment by alvestrand** [comment]
Seeing no further comments, I'm closing this issue.
