### ISSUE TITLE
Do we want a IANA registry of top-level types

### ISSUE THREAD

**Issue by duerst** [ietf-wg-mediaman/toplevel#3]
There is currently no IANA registry of top-level types; the top level types just listed under the heading "Registries included below" at https://www.iana.org/assignments/media-types/media-types.xhtml. Essentially, the idea would be to just add a pointer to the defining RFC for each top-level type.
I think we should do this because it helps improve documentation, and would also help potential registrants. For example, I had difficulties finding the relevant RFC for the 'model' type.

**Comment by alvestrand** [comment]
If there is no single RFC that lists them all (and there isn't), I think an IANA registry is necessary.
Today, the "Registries included below" section of https://www.iana.org/assignments/media-types/media-types.xhtml functions as that registry, but a fully specified registry is, in my opinion, better.

That requires adding an "IANA considerations" section in the draft that specifies the format of the registry and the initial content.

**Comment by aamelnikov** [comment]
It is quite hard to find RFCs for some of the top media types, for example for "model", so I support having a registry.

**Comment by duerst** [comment]
For the registry, for each type, just its name, a pointer to the relevant RFC, and a pointer to the registration of subtypes may be enough. If any other columns seem to make sense, please say so.

**Comment by alvestrand** [comment]
"a pointer to the registration of subtypes" = "a pointer to IANA's registry of subtypes for that type"?
If so, I agree with Martin.

**Comment by alvestrand** [comment]
I think we have consensus that we should propose a registry.

**Comment by duerst** [comment]
Addressed with commit 3a5636a6f27a. @alvestrand: please close if you think this is okay.

**Comment by alvestrand** [comment]
Read and agreed that this is closable.
