### ISSUE TITLE
Where to put background/justification info

### ISSUE THREAD

**Issue by duerst** [ietf-wg-mediaman/toplevel#4]
The 'background story' is currently (-01) distributed among various places:
- The "1.1.  Background" section contains some general background info.
- Most of the criteria in Section 2 contain some explanation about the 'why'.
- "3.  Top-Level Media Type History" contains additional background info.
Currently, there's probably quite some overlap between the above three.
Any advice on where to put this information, how much is needed,... is highly appreciated.

**Comment by alvestrand** [comment]
I think the current division (most of the history and background is in section 3, you don't need to read section 1 and 2 to get the picture) is OK.

**Comment by alvestrand** [comment]
Closing as "no change needed".
