### ISSUE TITLE
Should we use SHOULD and friends?

### ISSUE THREAD

**Issue by duerst** [ietf-wg-mediaman/toplevel#5]
The current draft (-01) sometimes has MUST and friends, and sometimes just uses lower case or some other words. I think we should decide which way to go (which may be a middle ground such as MUST for the really important stuff,...).

**Comment by alvestrand** [comment]
MUST (and SHOULD and MAY) is a formal requirement.
BCP 14 (RFC 2119 and RFC 8174) says that they're only formal requirements when they're uppercase.

We MUST (pun intended) ensure that 1) all formal requirements use uppercase, and 2) that no colloquial use of the word is written in uppercase.

**Comment by alvestrand** [comment]
In -01, there is "A top-level type must not be defined for the mapping of other protocol elements to media types." - this could be a "MUST NOT".

There are two other lower-case "must", but these are quotes, so should reflect the capitalization used in the source of the quote.

**Comment by alvestrand** [comment]
For SHOULD, there is a lot of lowercase "should" in section 2.1 bullets 4 and 5. Not clear if they're colloquial or normative, or a mix.

in section 2.3, "A new top-level type should not generate aliases for existing widely used types or subtypes." can probably be a SHOULD NOT.

"neither should be used" should be reformulated for clarity - "Top level types with an "X-" prefix cannot be registered, and SHOULD NOT be used".

The "should" in section 3 is a quote.

**Comment by duerst** [comment]
Addressed with commits cd4d9adb15b5 and f14c36c51250.
@alvestrand: I mostly followed your suggestions; please feel free to close.

**Comment by alvestrand** [comment]
Closing as requested.
