### ISSUE TITLE
Require documentation of common parameters (if there are such common parameters) ?

### ISSUE THREAD

**Issue by duerst** [ietf-wg-mediaman/toplevel#6]
Should we add a point about common parameters to 2.1. Required Criteria? We have a point in 2.2, saying that a need for common parameters may be an indication of a new top-level type. But we don't require in 2.1 that common parameters have to be document if there are some.

**Comment by duerst** [comment]
Currently the only known cases are 'charset' for text/* and 'boundary' for multipart/*. See also the discussion starting at https://mailarchive.ietf.org/arch/msg/media-types/qapqDPOznqt1FzV6pMxFeuUexnI. Related to https://github.com/ietf-wg-mediaman/toplevel/issues/7.

**Comment by alvestrand** [comment]
Seems like there's no strong desire to do so. Might make sense, but might also make sense to not require it (it duplicates information from the registering RFC).

**Comment by alvestrand** [comment]
Closing as "no action needed".
