### ISSUE TITLE
Add common parameters to registry entries?

### ISSUE THREAD

**Issue by duerst** [ietf-wg-mediaman/toplevel#7]
Should we add common parameters to the registry entries? This could be done with a new column, or in the comment field.
(Currently the only known cases are 'charset' for text/* and 'boundary' for multipart/*.)

**Comment by duerst** [comment]
See also the discussion starting at https://mailarchive.ietf.org/arch/msg/media-types/qapqDPOznqt1FzV6pMxFeuUexnI. Related to https://github.com/ietf-wg-mediaman/toplevel/issues/6.

**Comment by alvestrand** [comment]
Seems like there's no strong desire to do so. Might make sense, but might also make sense to not require it (it duplicates information from the registering RFC).

**Comment by alvestrand** [comment]
Closing as "no action needed".
