### ISSUE TITLE
IANA would like the initial content of the toplevel registry to be explicitly specified

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mediaman/toplevel#8]
From Amanda Baber, IANA:

IANA is actually being asked to create a registry, but we haven't been told how to fully populate it. This is what we've pieced together:

Name: Top-Level Media Types
Reference: this document
Registration Procedure: Standards Action

Type | Reference | Comment
Application | ? |
Audio | ? |
Font | RFC 8081 |
Example | RFC 4735 |
Image | ? |
Message | ? |
Model | RFC 2077 | 
Multipart | ? |
Text | ? |
Video | ? |
 
The narrative in Section 3 (not part of the IANA Considerations section) appears to indicate that RFC 1341 should be listed as the reference for the other types, but when we were revising the media type submission form (for submissions outside for RFCs), the designated experts told us that RFC 2046 was the relevant document, as recording in the "Type Name" menu: https://www.iana.org/form/media-types

The IANA Considerations section also says that the comment field "may" list "requires CRLF for newlines" for the "text" registration and "no registrations, for examples only" for the "example" registration, but IANA cannot determine whether to implement those suggestions. 

We strongly prefer that a table or list of registrations that tells us how to populate each field in the new registry be added to the IANA Considerations section.

**Comment by alvestrand** [comment]
Proposed resolution: Include the table in the IANA considerations section.
The missing RFCs should be RFC 2046.

**Comment by duerst** [comment]
Addressed (I hope) with https://github.com/ietf-wg-mediaman/toplevel/commit/eca02675f552.

**Comment by alvestrand** [comment]
Do you have a link to your current doc at head? It is not checked in as
html or text.

søn. 5. nov. 2023, 02:43 skrev Martin Dürst ***@***.***>:

**Comment by duerst** [comment]
I'll supply a new version in an hour or so.

Regards,   Martin.

**Comment by duerst** [comment]
Hello Harald,

I just submitted -04. It's not yet really all the changes I wanted to 
include, but really almost there. I'm going to board my flight to SFO 
now. In SF, I'll be on a hike during Sunday, but should be able to fix 
things up my (Pacific time) Sunday evening. If you have any suggestions 
about what needs more work, that would be appreciated (my understanding 
is that I answered all LC comments except Lars's, but most of his are 
also addressed already, and an email responding to him is already almost 
done).

Please enjoy the IETF in Prague, and say hello to everybody from me.

Regards,   Martin.

**Comment by alvestrand** [comment]
-04 section 4.2 looks good to me
